"""Add budget tables with proper relationships

Revision ID: 1987a9834fed
Revises: 
Create Date: 2026-03-23 14:53:10.184097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1987a9834fed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'])
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('church_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'budget_categories', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'churches', ['church_id'], ['id'])
        batch_op.drop_column('requested_amount')
        batch_op.drop_column('approved_amount')
        batch_op.drop_column('budget_id')

    with op.batch_alter_table('budget_comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('variance', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('variance_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('budget_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('january', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('february', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('march', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('april', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('may', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('june', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('july', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('august', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('september', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('october', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('november', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('december', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('fiscal_year',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('church_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('previous_amount')
        batch_op.drop_column('rejected_date')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_amount')
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('approved_date')
        batch_op.drop_column('submitted_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('approved_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('approved_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rejected_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('previous_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['submitted_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['rejected_by'], ['id'])
        batch_op.alter_column('church_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('fiscal_year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('approved_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('december')
        batch_op.drop_column('november')
        batch_op.drop_column('october')
        batch_op.drop_column('september')
        batch_op.drop_column('august')
        batch_op.drop_column('july')
        batch_op.drop_column('june')
        batch_op.drop_column('may')
        batch_op.drop_column('april')
        batch_op.drop_column('march')
        batch_op.drop_column('february')
        batch_op.drop_column('january')
        batch_op.drop_column('budget_type')
        batch_op.drop_column('variance_percentage')
        batch_op.drop_column('variance')
        batch_op.drop_column('actual_amount')
        batch_op.drop_column('account_code')
        batch_op.drop_column('account_id')
        batch_op.drop_column('period')

    with op.batch_alter_table('budget_comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('approved_amount', sa.NUMERIC(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('requested_amount', sa.NUMERIC(precision=15, scale=2), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'budgets', ['budget_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('church_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('budget_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
