"""make approver_id nullable

Revision ID: 86b27828917e
Revises: 
Create Date: 2026-03-16 23:12:44.050839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b27828917e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
