"""Add payroll workflow with proper relationships

Revision ID: a9a6a5af85ab
Revises: 
Create Date: 2026-03-24 11:44:00.857215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a6a5af85ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initiated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('initiated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('calculated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calculated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('calculation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approval_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('journal_entry_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attachment_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('attachment_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment_verified_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['initiated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['processed_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['attachment_uploaded_by'], ['id'])
        batch_op.create_foreign_key(None, 'journal_entries', ['journal_entry_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['calculated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['attachment_verified_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['submitted_by'], ['id'])
        batch_op.drop_column('attachment_verified_at')
        batch_op.drop_column('attachment_verified_by')
        batch_op.drop_column('attachment_verified')
        batch_op.drop_column('attachment_uploaded_at')
        batch_op.drop_column('attachment_uploaded_by')
        batch_op.drop_column('attachment_filename')
        batch_op.drop_column('attachment_path')
        batch_op.drop_column('journal_entry_id')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('processed_by')
        batch_op.drop_column('approval_comments')
        batch_op.drop_column('review_comments')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('calculation_notes')
        batch_op.drop_column('calculated_at')
        batch_op.drop_column('calculated_by')
        batch_op.drop_column('initiated_at')
        batch_op.drop_column('initiated_by')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
